---
- name: Check if FIPS is enabled
  command: cat /proc/sys/crypto/fips_enabled
  register: fips
  changed_when: false

- name: Enable FIPS mode
  command: fips-mode-setup --enable
  when: fips.stdout | int == 0

- name: Reboot
  reboot:
  when: fips.stdout | int == 0
